language: php
sudo: required
dist: trusty
php:
 - hhvm
 - hhvm-nightly
 - hhvm-3.18
 - hhvm-3.15
 - hhvm-3.12
install: hhvm --php $(which composer) install;
script:
 - hh_client
 - hhvm vendor/bin/phpunit
